######################################################################
# Automatically generated by qmake (3.0) Sat Oct 1 23:52:52 2016
######################################################################

TEMPLATE = app
TARGET = QJsonDocument-from-Json
INCLUDEPATH += .

# Input
SOURCES += qjsondocument-from-json.cpp
