######################################################################
# Automatically generated by qmake (3.0) Sat Oct 1 23:52:52 2016
######################################################################

TEMPLATE = app
TARGET = QSvgRenderer
INCLUDEPATH += .

QT += svg

# Input
SOURCES += qsvgrenderer.cpp

LIBS += -L/home/peter/dev/fuzzers -lFuzzer
