######################################################################
# Automatically generated by qmake (3.0) Sat Oct 1 23:52:52 2016
######################################################################

TEMPLATE = app
TARGET = QJsonDocument-from-binary-data
INCLUDEPATH += .

# Input
SOURCES += qjsondocument-from-binary-data.cpp

LIBS += -lFuzzer
