######################################################################
# Automatically generated by qmake (3.0) Sat Oct 1 23:52:52 2016
######################################################################

TEMPLATE = app
TARGET = QImage-from-data
INCLUDEPATH += .

# Input
SOURCES += qimage-from-data.cpp
