######################################################################
# Automatically generated by qmake (3.0) Sat Oct 1 23:52:52 2016
######################################################################

TEMPLATE = app
TARGET = qtnetwork-http
INCLUDEPATH += .

QT = core network

# Input
SOURCES += qtnetwork-http.cpp

LIBS += -L/home/peter/dev/fuzzers -lFuzzer
